### ISSUE TITLE
SysOps: organize issues required to add SysOp administration.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/CommunityKitPublic#172]
SysOp features are really starting to slow me down. Can I re-prioritize these issues?

- [ ] Client notes interface: 4 hours. #170
- [ ] Server: on mute, stop player from communicating, and check mute when player tries to communicate. 2 hours. #169
- [ ] Server: on ban, disconnect player, send player message about ban, and check ban when player tries to communicate. 2 hours. #168
- [ ] Server: accept message setting player SysOp level. 1 hour. #171
- [ ] Server/Client: allow log in as SysOp. 1 hour. #173
- [ ] Server/Client: on log in as SysOp, enumerate SysOp powers allowed to client. 1 hour. #174

**Comment by ZaneDubya** [comment]
Closing - no need for this feature in a low population game.
